services:
  lms:
    container_name: lms
    image: lmscommunity/lyrionmusicserver
    volumes:
      - /opt/docker/lms/config:/config:rw
      - /opt/daten/musik:/music:ro
      - /opt/docker/lms/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    environment:
      - HTTP_PORT=9000
    restart: always
    networks:
      local-home-net:
        ipv4_address: 192.168.178.3

networks:
  local-home-net:
    external: true
