services:
  navidrome:
    image: deluan/navidrome:latest
    #user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_SCANNER_ENABLED: true
      ND_SCANNER_SCHEDULE: 0 9 * * *
    volumes:
      - /opt/docker/navidrome:/data
      - /opt/daten/musik:/music:ro
