services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /opt/docker/tvheadend/data:/config
      - /opt/docker/tvheadend/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    restart: unless-stopped
